export const BASE_URL_SUPPLEMENT: Record<string, string> = {
  anthropic: "https://api.anthropic.com",
  openai: "https://api.openai.com",
  groq: "https://api.groq.com/openai/v1",
  mistral: "https://api.mistral.ai/v1",
  together: "https://api.together.xyz/v1",
  togetherai: "https://api.together.xyz/v1",
  "fireworks-ai": "https://api.fireworks.ai/inference/v1",
  perplexity: "https://api.perplexity.ai",
  cohere: "https://api.cohere.com/v1",
  cerebras: "https://api.cerebras.ai/v1",
  deepseek: "https://api.deepseek.com/v1",
  openrouter: "https://openrouter.ai/api/v1",
  "github-models": "https://models.inference.ai.azure.com",
  deepinfra: "https://api.deepinfra.com/v1/openai",
  nvidia: "https://integrate.api.nvidia.com/v1",
  xai: "https://api.x.ai/v1",
  "cloudflare-workers-ai": "https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1",
  "ollama-cloud": "https://ollama.com/api",
  ollama: "http://localhost:11434/v1",
  lmstudio: "http://localhost:1234/v1",
  "alibaba": "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
  "alibaba-cn": "https://dashscope.aliyuncs.com/compatible-mode/v1",
  "google": "https://generativelanguage.googleapis.com/v1beta/openai",
  "google-vertex": "https://aiplatform.googleapis.com/v1",
  azure: "https://{resource}.openai.azure.com/openai/v1",
  "amazon-bedrock": "https://bedrock-runtime.{region}.amazonaws.com",
};


